### register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username" : "jackson1",
  "password" : "123456",
  "email" : "jackson@163.com"
}

### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username" : "jackson1",
  "password" : "123456"
}

> {%
    client.global.set("token", response.body.data.token)
%}

### info
GET http://localhost:8080/api/users/info
Authorization: Bearer {{token}}


### post create
POST http://localhost:8080/api/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "My first post",
  "content": "This is the content of my first post."
}

### post list
GET http://localhost:8080/api/posts?page=1&size=10

### post update
PUT http://localhost:8080/api/posts/6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "My first post(updated)1",
  "content": "This is the content of my first post.(updated)1"
}

### post delete
DELETE http://localhost:8080/api/posts/6
Authorization: Bearer {{token}}

### post comment
POST http://localhost:8080/api/posts/1/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "Great post!111"
}

### post comments list
GET http://localhost:8080/api/posts/1/comments






